You have passed `None` for safety_checker to disable its functionality in <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>. Note that this might lead to problems when using <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> and is not recommended.
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Load stable_diffusion_model:v14 from wandb cloud checkpoint
Output will be saved in ../book dataset/v14 inference
model running on device cuda:0
Generating images on the test set to compute FID score......
0 images already generated. Skipping them...



100%|███████████████████████████████████████████| 50/50 [00:09<00:00,  5.39it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wenxuan/Stable-diffusion-for-book-cover-generation/sd-inference.py", line 435, in <module>
    get_fid_images(pipeline, save_dir)
  File "/home/wenxuan/Stable-diffusion-for-book-cover-generation/sd-inference.py", line 203, in get_fid_images
    img.save(os.path.join(args.save_dir,name+'.jpg'))
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/pandas/core/ops/common.py", line 72, in new_method
    return method(self, other)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/pandas/core/arraylike.py", line 102, in __add__
    return self._arith_method(other, operator.add)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/pandas/core/series.py", line 6259, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/pandas/core/base.py", line 1325, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 226, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 165, in _na_arithmetic_op
    result = func(left, right)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U4')) -> None