2022-12-10 18:24:45,497 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Configure stats pid to 155853
2022-12-10 18:24:45,497 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:24:45,497 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:24:45,497 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:24:45,497 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:24:45,497 INFO    MainThread:155853 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182445-zw0344ea/logs/debug.log
2022-12-10 18:24:45,498 INFO    MainThread:155853 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182445-zw0344ea/logs/debug-internal.log
2022-12-10 18:24:45,498 INFO    MainThread:155853 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:24:45,498 INFO    MainThread:155853 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:24:45,498 INFO    MainThread:155853 [wandb_init.py:init():569] starting backend
2022-12-10 18:24:45,498 INFO    MainThread:155853 [wandb_init.py:init():573] setting up manager
2022-12-10 18:24:45,502 INFO    MainThread:155853 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-10 18:24:45,506 INFO    MainThread:155853 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:24:45,508 INFO    MainThread:155853 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:24:45,525 INFO    MainThread:155853 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:24:45,626 ERROR   MainThread:155853 [wandb_init.py:init():713] encountered error: resume='must' but run (zw0344ea) doesn't exist
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Configure stats pid to 155853
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182520-fbdkp0mg/logs/debug.log
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182520-fbdkp0mg/logs/debug-internal.log
2022-12-10 18:25:20,601 INFO    MainThread:155853 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:25:20,602 INFO    MainThread:155853 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:25:20,602 INFO    MainThread:155853 [wandb_init.py:init():569] starting backend
2022-12-10 18:25:20,602 INFO    MainThread:155853 [wandb_init.py:init():573] setting up manager
2022-12-10 18:25:20,603 INFO    MainThread:155853 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-10 18:25:20,604 INFO    MainThread:155853 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:25:20,606 INFO    MainThread:155853 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:25:20,612 INFO    MainThread:155853 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:26:20,629 ERROR   MainThread:155853 [wandb_init.py:init():704] backend process timed out
2022-12-10 18:26:20,629 ERROR   MainThread:155853 [wandb_init.py:init():713] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Configure stats pid to 155853
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/settings
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182628-zw0344ea/logs/debug.log
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Stable-diffusion-for-book-cover-generation/Output_images/v12 inference/wandb/run-20221210_182628-zw0344ea/logs/debug-internal.log
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_init.py:init():516] calling init triggers
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-10 18:26:28,729 INFO    MainThread:155853 [wandb_init.py:init():569] starting backend
2022-12-10 18:26:28,730 INFO    MainThread:155853 [wandb_init.py:init():573] setting up manager
2022-12-10 18:26:28,731 INFO    MainThread:155853 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-10 18:26:28,732 INFO    MainThread:155853 [wandb_init.py:init():580] backend started and connected
2022-12-10 18:26:28,734 INFO    MainThread:155853 [wandb_init.py:init():658] updated telemetry
2022-12-10 18:26:28,741 INFO    MainThread:155853 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-10 18:26:28,827 WARNING MsgRouterThr:155853 [router.py:message_loop():77] message_loop has been closed
2022-12-10 18:27:20,774 WARNING MainThread:155853 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/wenxuan/sd_training/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-12-10 18:28:20,737 WARNING MsgRouterThr:155853 [router.py:message_loop():77] message_loop has been closed
2022-12-10 18:28:20,738 WARNING MsgRouterThr:155853 [router.py:message_loop():77] message_loop has been closed
